version: "3"
services:

   db:
     image: postgres:9.6
     restart: always
     environment:
       POSTGRES_PASSWORD: beto364
       POSTGRES_DB: beto364
     ports:
       - 5432:5432
     volumes:
       - ./postgres-data:/bitnami/postgresql/data
